var a = 10;
var b = 20;

console.log(b)

b = 5;
console.log(a,b)

//---------------------//

var a = 30;
var b = 20;
var c = a+b;
console.log (c)

b = 10;
console.log(b,c)

c = a+b;
console.log(a,b,c)

//---------------------//

var a = 10;
var b = 20;
var c = a;
var b = c;
var a = b;
console.log(a,b,c)

//---------------------//

var a = 10;
var b = a+1;
var a = b+1;
var b = a+1;
console.log(a)

var a = b+1;
console.log(a,b)

//---------------------//

nota1 = 10
nota2 = 8
nota3 = 3

media = nota1*2+nota2*3+nota3*5

mediafinal = media/10

console.log(mediafinal)